default:
  image: ruby:2.7.2
  before_script:
    - apt-get update -qy
    - apt-get install -y lftp
    - bundle install

cache:
  paths:
    - .vendor/
    - vendor/

stages:
  - build
  - deploy

build:
  stage: build
  script: 
    - bundle exec jekyll b -d _site
  artifacts:
    paths:
      - _site
  only:
    - master
  
deploy:
  stage: deploy
  script:
    - set ftp:list-options -a
    - lftp -e "set ftp:list-options -a; open ftp.stackcp.com; user $FTP_U $FTP_P; mirror --reverse --verbose --delete _site/ /; bye"
  only:
    - master_ftp

deploy_scp:
  stage: deploy-scp
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - scp -r _site miokimia.com@ssh.stackcp.com:/home/sites/14b/e/e8334152a8/public_html
  only: 
    - master