# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            miokimia
tagline:          'A Personal Blog and learning notes'
description:      'myokymia: An involuntary spontaneous quivering of part of a muscle, insufficient to move a joint.'
url:              http://miokimia.com
baseurl:          /

author:
  name:           'Mundo'
  url:            https://miokimia.com

include: 
  - _pages

# plugins
plugins: [jekyll-gist, jekyll-sitemap, jekyll-seo-tag]

# Custom vars
version:          2.1.0

github:
  repo:           https://gitlab.com/mundo03/miokimia.com
